[general]
seed = 1234

[path]
worms_dataset = '/home/ashkan/workspace/deployed/worms_nuclei_metric_learning-deployed/data/processed/worms_dataset_debug'

[train]
n_step = 50
model_ckpt_every_n_step = 10
running_loss_interval = 5
burn_in_step = 15
lr_drop_patience = 2

[data]
patch_size = [32, 32, 32]
n_worker = 1
