name = 'default'

[general]
debug = true
#overwrite = true
seed = 1234

[path]
#experiment_root = NONE
worms_dataset = '/home/ashkan/workspace/deployed/worms_nuclei_metric_learning-deployed/data/processed/worms_dataset'

[model]
model_name = 'unet'
model_params = [4, 8, 4, 6]
init_model_last = false

[data]
n_worker = 10
input_size = [64, 64, 64]
output_size = [54, 54, 54]
n_consistent_worms = 2  # only implemented for 1 and 2
use_coord = true
max_ninstance = 110
min_label_volume = 10
cpm_dataset = '/home/ashkan/workspace/deployed/worms_nuclei_metric_learning-deployed/data/processed/cpm_dataset.pkl'
samples_per_volume_for_training = 3

[data.common_transforms]
rescaleintensity01 = true

[data.train_transforms]
random_flip = 0

[data.train_transforms.random_affine]
scale = 0.2
translation = 10
degree = 10
p = 0

[data.train_transforms.random_elastic]
num_control_points = [6, 6, 20]
max_displacement = [15, 15, 15]
p = 0.5

[train]
n_cluster = 558
n_step = 100000
model_ckpt_every_n_step = 20000
running_loss_interval = 1000
burn_in_step = 50000
learning_rate = 0.0001
weight_decay = 0
lr_drop_factor = 0.1
lr_drop_patience = 20

